version: '3'
services:
  cachet-monitor:
  # This docker-compose.yml file should exist OUTSIDE of the source directory! Otherwise change paths
    build: ./cachet-monitor/
  volumes:
    - ./Config.json:/app/Config.json
    - ./Data.json:/app/Data.json
